name: build-test
on:  workflow_dispatch

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.js 12.x
      uses: actions/setup-node@master
      with:
        node-version: 12.x
        
    - name: Install dependencies
      run: |
         sudo apt-get -yqq install libpq-dev build-essential libcurl4-openssl-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          yarn install

    - name: npm install
      run: npm install
   #   run: npm cache clean --force

    - name: Lint
  #    run: npm run lint:fix
      run: npm run format-check


    - name: npm test
      run: npm test
